console.log("Hello World");
console.log(123);
console.log(true);
var greeting="Hello World";
console.log(greeting);
console.log([1,2,3,4]);
console.log({a:1,b:2});
console.table({a:1,b:2});
console.error("This is an erroe msg");
console.timeEnd();